[package]
name = "zellij-bookmarks"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
owo-colors = "4.1.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_yaml = "0.9.34"
zellij-tile = "0.41.2"
zellij-utils = "0.41.2"